{% set name = "hubspot-api-client" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hubspot-api-client-{{ version }}.tar.gz
  sha256: dfd0cd025659f4e7eb578eb029b6529649c7b8dddc916613d52b44665533dd8d

build:
  noarch: python
  script:
    - echo {{ version }} > {{ SRC_DIR }}/VERSION
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - six >=1.9
  run:
    - python >=3.8
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

test:
  imports:
    - hubspot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HubSpot/hubspot-api-python
  summary: HubSpot API client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
