{% set name = "hubspot-api-client" %}
{% set version = "11.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 93ed914f1cd4dad67bacf26b8a1ec8506847483fa801cb2bddd4b2d887d0f825

build:
  noarch: python
  script:
    - echo {{ version }} > {{ SRC_DIR }}/VERSION
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - six >=1.9
    - setuptools
  run:
    - python >={{ python_min }}
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil
    - requests

test:
  imports:
    - hubspot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/HubSpot/hubspot-api-python
  summary: HubSpot API client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
